import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-bg-primary">
      {/* <head>Test</head> */}
      <body className="flex flex-col max-w-6xl mx-4 mt-8 mb-40 md:flex-row lg:mx-auto">
        <main className={inter.className}>
          {/* Nav to go here */}
          {children}
        </main>
      </body>
    </html>
  );
}
